name: simple_log
description: A simple way to upload logs to avenge.cn. avenge.cn is a log management platform, welcome to try.
version: 1.0.5
author: creatint <creatint@163.com>
homepage: https://github.com/creatint/flutter_simple_log

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  http: ^0.12.1

dev_dependencies:
  test: ^1.6.0

