name: simple_log
description:
  A simple way to upload logs to remote server, support all platforms, dart-native, dart-js, flutter-android, flutter-ios, flutter-web, flutter-windows, flutter-linux, flutter-mac.
version: 1.0.8
author: creatint <creatint@163.com>
homepage: https://github.com/creatint/flutter_simple_log

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  http: ^0.12.1

dev_dependencies:
  test: ^1.6.0

